module.exports = {
  BISTSirketleri: "IGS",
  YatirimKuruluslari: "YK",
  PortfoyYonetimSirketleri: "PYS",
  DuzenleyiciDenetleyiciKurumlar: "DDK",
  DigerKAPUyeleri: "DG",
  BorsaYatirimFonu: "BYF",
  YatirimFonu: "YF",
  EmeklilikYatirimFonu: "EYF",
  OKSEmeklilikYatirimFonu: "OKS",
  YabanciYatirimFonu: "YYF",
  VarlikFinansmanFonu: "VFF",
  KonutFinansmanFonu: "KFF",
  GayrimenkulYatirimFonu: "GMF",
  GirisimSermayesiYatirimFonu: "GSF",
  ProjeFinansmanFonlari: "PFF",
};
