module.exports = {
  IGS: "BIST Şirketleri",
  YK : "Yatırım Kuruluşları",
  PYS: "Portföy Yönetim Şirketleri",
  DDK: "Düzenleyici Denetleyici Kurumlar",
  DG : "Diğer KAP Üyeleri",
  BYF: "Borsa Yatırım Fonu",
  YF : "Yatırım Fonu",
  EYF: "Emeklilik Yatırım Fonu",
  OKS: "OKS Emeklilik Yatırım Fonu",
  YYF: "Yabancı Yatırım Fonu",
  VFF: "Varlık Finansman Fonu",
  KFF: "Konut Finansman Fonu",
  GMF: "Gayrimenkul Yatırım Fonu",
  GSF: "Girişim Sermayesi Yatırım Fonu",
  PFF: "Proje Finansman Fonları",
};
